export const FETCH_POSTS = 'POST/FETCH_POSTS'
export const REQUEST_POSTS = 'POST/REQUEST_POSTS'

export const UPLOAD_POST = 'POST/UPLOAD_POST'
export const UPLOAD_POST_SUCCESS = 'POST/UPLOAD_POST_SUCCESS'

export const SET_CURRENT_PAGE = 'POSTS/SET_CURRENT_PAGE'

export const SEARCH_POST = 'POSTS/SEARCH_POST'

export const GET_COMMENTS = 'COMMENTS/GET_COMMENTS'
export const GET_COMMENTS_SUCCESS = 'COMMENTS/GET_COMMENTS_SUCCESS'

export const CREATE_NEW_USER = 'USERS/CREATE_NEW_USER'
export const CREATE_EMAIL_NEW_USER = 'USERS/CREATE_EMAIL_NEW_USER'
export const CREATE_PASSWORD_NEW_USER = 'USERS/CREATE_PASSWORD_NEW_USER'
export const CREATE_NEW_USER_SUCCESS = 'USERS/CREATE_NEW_USER_SUCCESS'


